### PR TITLE
Initialize Roundcube using iniset.php include only

### PR DESCRIPTION
**Pull request by mvorisek**
address https://github.com/roundcube/roundcubemail/pull/9407#issuecomment-2041487898

I tested it using:

```diff

     "require": {
         ...
-        "roundcube/plugin-installer": "~0.3.3",
+        "roundcube/plugin-installer": "dev-master#f46bcea6d10c9a831c07f71fed3a0fea4a70eaa4 as 0.3.3",
```

### CODE REVIEW

**Comment by mvorisek** [comment]
If PR looks good, please merge and tag a new release.

**Comment by mvorisek** [comment]
@alecpl tested with #46, can this PR be merged?

**Comment by mvorisek** [comment]
@alecpl can a new release be tagged for #9407?

**Comment by alecpl** [comment]
0.3.4 tag pushed.

**Pull request merged**
